EscuelaDeEsqui/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using EscuelaDeEsqui.APIs.Application.ViewModel.Client;
using EscuelaDeEsqui.APIs.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace EscuelaDeEsqui.Controllers
{
    public class ClientsController : Controller
    {
        public IActionResult Create()
        {
            return View(new Create());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Create create)
        {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Client/New", create);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Create));
            }
            else
            {
                return (View());
            }
        }
        public IActionResult SearchClient()
        {
            return View(new SearchResult());
        }
        [HttpPost]
        public async Task<IActionResult> SearchClient(SearchResult searchResult)
        {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Client/SearchClient", searchResult.search);
                response.EnsureSuccessStatusCode();
                searchResult.searches = await response.Content.ReadAsAsync<IEnumerable<Search>>();
                return View(searchResult);
            }
            else
            {
                return View(searchResult);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ViewClientInformation(int ClientId)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("https://localhost:5002/");
            HttpResponseMessage response = await Client.PostAsJsonAsync("api/Client/ClientInformation", ClientId);
            response.EnsureSuccessStatusCode();
            return View(await response.Content.ReadAsAsync<PersonalInformation>());
        }
        [HttpPost]
        public IActionResult ViewClientInformation(PersonalInformation personalInformation)
        {
            return RedirectToAction(nameof(SearchClient));
        }
        public async Task<IActionResult> Edit(int ClientId)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("https://localhost:5002/");
            HttpResponseMessage response = await Client.PostAsJsonAsync("api/Client/GetEditClient", ClientId);
            response.EnsureSuccessStatusCode();
            return View(await response.Content.ReadAsAsync<Edit>());
        }
        [HttpPost]
        public async Task<IActionResult> Edit(Edit edit)
        {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Client/EditClient", edit);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(SearchClient));
            }
            else
            {
                return View(edit);
            }
        }
    }
}

EscuelaDeEsqui/Controllers/LessonsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using EscuelaDeEsqui.APIs.Application.ViewModel.Lesson;
using Microsoft.AspNetCore.Mvc;

namespace EscuelaDeEsqui.Controllers
{
    public class LessonsController : Controller
    {
        public IActionResult Create()
        {
            return View(new Create());
        }
        [HttpPost]
        public async Task<IActionResult> Create(Create create)
        {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Lesson/NewLesson", create);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Create));
            }
            else
            {
                return View(create);
            }
        }
        
    }
}

EscuelaDeEsqui/Controllers/TeachersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using EscuelaDeEsqui.APIs.Application.ViewModel.Teacher;
using System.Net.Http;
using EscuelaDeEsqui.APIs.ViewModel;

namespace EscuelaDeEsqui.Controllers
{
    public class TeachersController : Controller
    {
        public IActionResult Create()
        {
            return View(new Create());
        }

        [HttpPost]
        public async Task<IActionResult> Create(Create create)
        {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/New", create);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(Create));
            }
            else
            {
                return (View());
            }
        }
        public IActionResult SearchForTeacherInformation()
        {
            return View(new SearchResult());
        }
        [HttpPost]
        public async Task<IActionResult> SearchForTeacherInformation(SearchResult searchResult)
        {
            if(ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/SearchForInformation", searchResult.search);
                response.EnsureSuccessStatusCode();                
                searchResult.searches = await response.Content.ReadAsAsync<IEnumerable<Search>>();
                return View(searchResult);
            }
            else
            {
                return View(searchResult);
            }
        }
        [HttpGet]
        public async Task<IActionResult> ViewTeacherInformation(int TeacherId)
        {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("https://localhost:5002/");
            HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/TeacherInformation", TeacherId);
            response.EnsureSuccessStatusCode();
            return View(await response.Content.ReadAsAsync<PersonalInformation>());
        }
        [HttpPost]
        public IActionResult ViewTeacherInformation(PersonalInformation personalInformation)
        {
            return RedirectToAction(nameof(SearchForTeacherInformation));
        }
       public async Task<IActionResult> Edit(int TeacherId)
       {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("https://localhost:5002/");
            HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/GetEditTeacher", TeacherId);
            response.EnsureSuccessStatusCode();
            return View(await response.Content.ReadAsAsync<Edit>());
       }
       [HttpPost]
       public async Task<IActionResult> Edit(Edit edit)
       {
            if (ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/EditTeacher", edit);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(SearchForTeacherInformation));
            }
            else
            {
                return View(edit);
            }
       }
       public async Task<IActionResult> Disactive(int TeacherId)
       {
            HttpClient Client = new HttpClient();
            Client.BaseAddress = new Uri("https://localhost:5002/");
            HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/DisactivateTeacher", TeacherId);
            response.EnsureSuccessStatusCode();
            return RedirectToAction(nameof(SearchForTeacherInformation));
       }
       [HttpGet]
       public IActionResult Absence(int TeacherId)
       {
            return View(new NewAbsence());
       }
       [HttpPost]
       public async Task<IActionResult> Absence(NewAbsence newAbsence)
       {
            if(ModelState.IsValid)
            {
                HttpClient Client = new HttpClient();
                Client.BaseAddress = new Uri("https://localhost:5002/");
                HttpResponseMessage response = await Client.PostAsJsonAsync("api/Teacher/NewAbsence", newAbsence);
                response.EnsureSuccessStatusCode();
                return RedirectToAction(nameof(SearchForTeacherInformation));
            }
            else
            {
                return View(newAbsence);
            }
       }
    }
}

EscuelaDeEsqui/Views/Shared/Countries.cshtml
<option value="Afghanistan">Afghanistan</option>
<option value="Albania">Albania</option>
<option value="Algeria">Algeria</option>
<option value="Andorra">Andorra</option>
<option value="Angola">Angola</option>
<option value="Argentina">Argentina</option>
<option value="Armenia">Armenia</option>
<option value="Australia">Australia</option>
<option value="Austria">Austria</option>
<option value="Azerbaijan">Azerbaijan</option>
<option value="Bahamas">Bahamas</option>
<option value="Bahrain">Bahrain</option>
<option value="Bangladesh">Bangladesh</option>
<option value="Barbados">Barbados</option>
<option value="Belarus">Belarus</option>
<option value="Belgium">Belgium</option>
<option value="Belize">Belize</option>
<option value="Benin">Benin</option>
<option value="Bhutan">Bhutan</option>
<option value="Bolivia">Bolivia</option>
<option value="Bosnia-Herzegovina">Bosnia-Herzegovina</option>
<option value="Botswana">Botswana</option>
<option value="Brazil">Brazil</option>
<option value="Brunei">Brunei</option>
<option value="Bulgaria">Bulgaria</option>
<option value="Burkina">Burkina</option>
<option value="Burundi">Burundi</option>
<option value="Cambodia">Cambodia</option>
<option value="Cameroon">Cameroon</option>
<option value="Canada">Canada</option>
<option value="Cape Verde Islands">Cape Verde Islands</option>
<option value="Chad">Chad</option>
<option value="Chile">Chile</option>
<option value="China">China</option>
<option value="Colombia">Colombia</option>
<option value="Congo">Congo</option>
<option value="Costa Rica">Costa Rica</option>
<option value="Croatia">Croatia</option>
<option value="Cuba">Cuba</option>
<option value="Cyprus">Cyprus</option>
<option value="Czech Republic">Czech Republic</option>
<option value="Denmark">Denmark</option>
<option value="Djibouti">Djibouti</option>
<option value="Dominica">Dominica</option>
<option value="Dominican Republic">Dominican Republic</option>
<option value="Ecuador">Ecuador</option>
<option value="Egypt">Egypt</option>
<option value="El Salvador">El Salvador</option>
<option value="England">England</option>
<option value="Eritrea">Eritrea</option>
<option value="Estonia">Estonia</option>
<option value="Ethiopia">Ethiopia</option>
<option value="Fiji">Fiji</option>
<option value="Finland">Finland</option>
<option value="France">France</option>
<option value="Gabon">Gabon</option>
<option value="Gambia">Gambia</option>
<option value="Georgia">Georgia</option>
<option value="Germany">Germany</option>
<option value="Ghana">Ghana</option>
<option value="Greece">Greece</option>
<option value="Grenada">Grenada</option>
<option value="Guatemala">Guatemala</option>
<option value="Guinea">Guinea</option>
<option value="Guyana">Guyana</option>
<option value="Haiti">Haiti</option>
<option value="Honduras">Honduras</option>
<option value="Hungary">Hungary</option>
<option value="Iceland">Iceland</option>
<option value="India">India</option>
<option value="Indonesia">Indonesia</option>
<option value="Iran">Iran</option>
<option value="Iraq">Iraq</option>
<option value="Ireland">Ireland</option>
<option value="Italy">Italy</option>
<option value="Jamaica">Jamaica</option>
<option value="Japan">Japan</option>
<option value="Jordan">Jordan</option>
<option value="Kazakhstan">Kazakhstan</option>
<option value="Kenya">Kenya</option>
<option value="Kuwait">Kuwait</option>
<option value="Laos">Laos</option>
<option value="Latvia">Latvia</option>
<option value="Lebanon">Lebanon</option>
<option value="Liberia">Liberia</option>
<option value="Libya">Libya</option>
<option value="Liechtenstein">Liechtenstein</option>
<option value="Lithuania">Lithuania</option>
<option value="Luxembourg">Luxembourg</option>
<option value="Macedonia">Macedonia</option>
<option value="Madagascar">Madagascar</option>
<option value="Malawi">Malawi</option>
<option value="Malaysia">Malaysia</option>
<option value="Maldives">Maldives</option>
<option value="Mali">Mali</option>
<option value="Malta">Malta</option>
<option value="Mauritania">Mauritania</option>
<option value="Mauritius">Mauritius</option>
<option value="Mexico">Mexico</option>
<option value="Moldova">Moldova</option>
<option value="Monaco">Monaco</option>
<option value="Mongolia">Mongolia</option>
<option value="Montenegro">Montenegro</option>
<option value="Morocco">Morocco</option>
<option value="Mozambique">Mozambique</option>
<option value="Myanmar">Myanmar</option>
<option value="Namibia">Namibia</option>
<option value="Nepal">Nepal</option>
<option value="Netherlands">Netherlands</option>
<option value="New Zealand">New Zealand</option>
<option value="Nicaragua">Nicaragua</option>
<option value="Niger">Niger</option>
<option value="Nigeria">Nigeria</option>
<option value="North Korea">North Korea</option>
<option value="Norway">Norway</option>
<option value="Oman">Oman</option>
<option value="Pakistan">Pakistan</option>
<option value="Panama">Panama</option>
<option value="Papua New Guinea">Papua New Guinea</option>
<option value="Paraguay">Paraguay</option>
<option value="Peru">Peru</option>
<option value="the Philippines">the Philippines</option>
<option value="Poland">Poland</option>
<option value="Portugal">Portugal</option>
<option value="Qatar">Qatar</option>
<option value="Romania">Romania</option>
<option value="Russia">Russia</option>
<option value="Rwanda">Rwanda</option>
<option value="Saudi Arabia">Saudi Arabia</option>
<option value="Senegal">Senegal</option>
<option value="Serbia">Serbia</option>
<option value="Seychelles, the">Seychelles, the</option>
<option value="Sierra Leone">Sierra Leone</option>
<option value="Singapore">Singapore</option>
<option value="Slovakia">Slovakia</option>
<option value="Slovenia">Slovenia</option>
<option value="Solomon Islands">Solomon Islands</option>
<option value="Somalia">Somalia</option>
<option value="South Africa">South Africa</option>
<option value="South Korea">South Korea</option>
<option value="Spain">Spain</option>
<option value="Sri Lanka">Sri Lanka</option>
<option value="Sudan">Sudan</option>
<option value="Suriname">Suriname</option>
<option value="Swaziland">Swaziland</option>
<option value="Sweden">Sweden</option>
<option value="Switzerland">Switzerland</option>
<option value="Syria">Syria</option>
<option value="Taiwan">Taiwan</option>
<option value="Tajikistan">Tajikistan</option>
<option value="Tanzania">Tanzania</option>
<option value="Thailand">Thailand</option>
<option value="Togo">Togo</option>
<option value="Trinidad and Tobago">Trinidad and Tobago</option>
<option value="Tunisia">Tunisia</option>
<option value="Turkey">Turkey</option>
<option value="Turkmenistan">Turkmenistan</option>
<option value="Tuvalu">Tuvalu</option>
<option value="Uganda">Uganda</option>
<option value="Ukraine">Ukraine</option>
<option value="United Arab Emirates (UAE)">United Arab Emirates (UAE)</option>
<option value="United Kingdom (UK)">United Kingdom (UK)</option>
<option value="United States of America (USA)">United States of America (USA)</option>
<option value="Uruguay">Uruguay</option>
<option value="Uzbekistan">Uzbekistan</option>
<option value="Vanuatu">Vanuatu</option>
<option value="Vatican City">Vatican City</option>
<option value="Venezuela">Venezuela</option>
<option value="Vietnam">Vietnam</option>
<option value="Western Samoa">Western Samoa</option>
<option value="Yemen">Yemen</option>
<option value="Zaire">Zaire</option>
<option value="Zambia">Zambia</option>
<option value="Zimbabwe">Zimbabwe</option>
<option value="OTHER">Otra</option>

EscuelaDeEsqui/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EscuelaDeEsqui</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">EscuelaDeEsqui</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="TeachersDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Teachers
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="TeacherDropDown">
                            <li><a class="dropdown-item" asp-controller="Teachers" asp-action="Create">Create</a></li>
                            <li><a class="dropdown-item" asp-controller="Teachers" asp-action="SearchForTeacherInformation">Search Teacher</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="ClientsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Clients
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="ClientDropDown">
                            <li><a class="dropdown-item" asp-controller="Clients" asp-action="Create">Create</a></li>
                            <li><a class="dropdown-item" asp-controller="Clients" asp-action="SearchClient">Search Client</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-dark" href="#" id="LessonsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Lessons
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="LessonDropDown">
                            <li><a class="dropdown-item" asp-controller="Lessons" asp-action="Create">Create</a></li>
                            <li><a class="dropdown-item" asp-controller="Clients" asp-action="SearchClient">Search Client</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - EscuelaDeEsqui</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>